[project]
name = "sirl"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "brax>=0.14.2",
    "imageio>=2.37.3",
    "jax>=0.10.0",
    "katex>=0.0.4",
    "keyboard>=0.13.5",
    "mediapy>=1.2.6",
    "memory-profiler>=0.61.0",
    "mujoco>=3.7.0",
    "mujoco-mjx>=3.8.0",
    "natnet>=0.2.0",
    "numpy>=2.4.4",
    "onrobot>=0.1.0",
    "optimistix>=0.1.0",
    "pip>=26.1.1",
    "pythreejs>=2.4.2",
    "scipy>=1.17.1",
    "stable-baselines3>=2.8.0",
    "ur-rtde>=1.6.3",
    "urx>=0.11.0",
    "warp-lang>=1.13.0",
]

[dependency-groups]
dev = [
    "jupyter-book>=2.1.4",
    "jupyterlab>=4.5.6",
    "jupyterlab-myst>=2.6.0",
    "matplotlib>=3.10.8",
    "mystmd>=1.8.3",
    "numpy>=2.4.4",
]
